version: "3.8"
services:
  db:
    image: postgres:latest
    env_file:
      - ./server/.env-non-dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/db_init.sql
    ports:
      - 5434:5432

  server:
    image: server_image
    build:
      context: ./server/
    env_file:
      - ./server/.env-non-dev
    command: ["/diploma/docker/app.sh"]
    ports:
      - 8000:8000
    depends_on:
      - db
volumes:
  postgres-data:
