version: "3.8"
services:
  db:
    image: postgres:latest
    command: -c 'max_connections=500'
    env_file:
      - ./server/.env-non-dev
    stdin_open: true
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    image: server_image
    build:
      context: ./server/
    env_file:
      - ./server/.env-non-dev
    command: ["/diploma/docker/app.sh"]
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy

  client:
    image: client_image
    build:
      context: ./client/app/
    env_file:
      - ./server/.env-non-dev
    ports:
      - 9000:9000
    depends_on:
      - server

  generator:
    image: generator_image
    build:
      context: ./generator_main/
    env_file:
      - ./server/.env-non-dev
    depends_on:
      db:
        condition: service_healthy
volumes:
  postgres-data:
